"""empty message

Revision ID: 4b6b0c324113
Revises: 2fa2b47f8536
Create Date: 2024-05-13 14:48:26.411966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6b0c324113'
down_revision = '2fa2b47f8536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('under_sea_house_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_sea_house_table')
    # ### end Alembic commands ###
